version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ct_zookeeper
    ports:
      - "2181:2181"
    networks :
      udf_net1 :
        ipv4_address :  172.18.0.101
  kafka1:
    image: wurstmeister/kafka
    container_name: ct_kafka1
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.102
#      KAFKA_CREATE_TOPICS: "TEST_TOPIC:10:1"
      KAFKA_ZOOKEEPER_CONNECT: 172.18.0.101:2181
      KAFKA_NUM_NETWORK_THREADS : 10
      KAFKA_NUM_IO_THREADS : 20
      KAFKA_QUEUED_MAX_REQUESTS : 1000
      KAFKA_HEAP_OPTS : "-Xmx10240M -Xms1024M"
      KAFKA_SOCKET_SEND_BUFFER_BYTES : 2048000
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES : 2048000
    volumes:
      - /opt/docker/volumes/docker_vol_kafka/docker.sock:/var/run/docker.sock
    networks :
      udf_net1 :
        ipv4_address :  172.18.0.102
  kafka2:
    image: wurstmeister/kafka
    container_name: ct_kafka2
    depends_on: [ zookeeper ]
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.103
#      KAFKA_CREATE_TOPICS: "TEST_TOPIC:10:1"
      KAFKA_ZOOKEEPER_CONNECT: 172.18.0.101:2181
      KAFKA_NUM_NETWORK_THREADS : 10
      KAFKA_NUM_IO_THREADS : 20
      KAFKA_QUEUED_MAX_REQUESTS : 1000
      KAFKA_HEAP_OPTS : "-Xmx10240M -Xms1024M"
      KAFKA_SOCKET_SEND_BUFFER_BYTES : 2048000
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES : 2048000
    volumes:
      - /opt/docker/volumes/docker_vol_kafka/docker.sock:/var/run/docker.sock
    networks :
      udf_net1 :
        ipv4_address :  172.18.0.103
networks:
  udf_net1 :
    driver : bridge
    ipam:
      driver : default
      config :
        - subnet : 172.18.0.0/24
          gateway : 172.18.0.1
